// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCQx6TSba4gBMaIw0XFbZ3Yo71VmxS1SU',
    appId: '1:211428303989:web:75769e74aed2de0ea8c43c',
    messagingSenderId: '211428303989',
    projectId: 'sezon-app-6d877',
    authDomain: 'sezon-app-6d877.firebaseapp.com',
    storageBucket: 'sezon-app-6d877.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEKKQ-3wu3_KxUz_kIti4-mBVKkKyH3Ko',
    appId: '1:211428303989:android:b2cf03528c3c9da9a8c43c',
    messagingSenderId: '211428303989',
    projectId: 'sezon-app-6d877',
    storageBucket: 'sezon-app-6d877.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCK88F96V-yWqZHUoPF0q7iuSDoxvuqnpM',
    appId: '1:211428303989:ios:cc4fc9bbbdaeccb3a8c43c',
    messagingSenderId: '211428303989',
    projectId: 'sezon-app-6d877',
    storageBucket: 'sezon-app-6d877.appspot.com',
    androidClientId: '211428303989-5cemhgmprhkd7a8rn9h6kq65qef26gtd.apps.googleusercontent.com',
    iosClientId: '211428303989-52junaj9dghr71v6hpdk2t9tvkn7kctu.apps.googleusercontent.com',
    iosBundleId: 'com.example.sezonApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCK88F96V-yWqZHUoPF0q7iuSDoxvuqnpM',
    appId: '1:211428303989:ios:a3dab387809593b5a8c43c',
    messagingSenderId: '211428303989',
    projectId: 'sezon-app-6d877',
    storageBucket: 'sezon-app-6d877.appspot.com',
    androidClientId: '211428303989-5cemhgmprhkd7a8rn9h6kq65qef26gtd.apps.googleusercontent.com',
    iosClientId: '211428303989-pgmdi775mdfl4b8l4jr4koikbbj7sd81.apps.googleusercontent.com',
    iosBundleId: 'com.example.sezonApp.RunnerTests',
  );
}
